### ISSUE TITLE
Permission denied when trying to run UML kernel

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/continuous-integration2#349]
From https://github.com/ClangBuiltLinux/continuous-integration2/runs/5851165483?check_suite_focus=true:

```
2022-04-06T15:02:30.8947386Z ./boot-utils/boot-uml.sh: line 36: /__w/continuous-integration2/continuous-integration2/linux: Permission denied
2022-04-06T15:02:30.8949984Z ./boot-utils/boot-uml.sh: line 36: exec: /__w/continuous-integration2/continuous-integration2/linux: cannot execute: Permission denied
2022-04-06T15:02:30.8950879Z Traceback (most recent call last):
2022-04-06T15:02:30.8952695Z   File "/__w/continuous-integration2/continuous-integration2/./check_logs.py", line 272, in <module>
2022-04-06T15:02:30.8953655Z     boot_test(build)
2022-04-06T15:02:30.8955298Z   File "/__w/continuous-integration2/continuous-integration2/./check_logs.py", line 252, in boot_test
2022-04-06T15:02:30.8956209Z     run_boot(build)
2022-04-06T15:02:30.8957827Z   File "/__w/continuous-integration2/continuous-integration2/./check_logs.py", line 240, in run_boot
2022-04-06T15:02:30.8959041Z     raise e
2022-04-06T15:02:30.8960876Z   File "/__w/continuous-integration2/continuous-integration2/./check_logs.py", line 236, in run_boot
2022-04-06T15:02:30.8961664Z     subprocess.run(boot_cmd, check=True)
2022-04-06T15:02:30.8962019Z   File "/usr/lib/python3.10/subprocess.py", line 524, in run
2022-04-06T15:02:30.8964656Z     raise CalledProcessError(retcode, process.args,
2022-04-06T15:02:30.8965534Z subprocess.CalledProcessError: Command '['./boot-utils/boot-uml.sh', '-k', '/__w/continuous-integration2/continuous-integration2/linux']' returned non-zero exit status 126.
```

I am guessing that `linux` does not have the execute bit set when it is downloaded. I will triage this shortly.

**Comment by nickdesaulniers** [comment]
Doesn't it usually when built locally? Could this be something that tuxmake is doing?

**Comment by nathanchance** [comment]
Yes, when it is built, it is an executable. TuxMake does not mess that bit up, as it works locally. This is likely due to us downloading the image from the Internet, as I don't think permissions transfer that way.

```
$ curl -LOSs https://builds.tuxbuild.com/27QL6ht9S7MI5VYg3aJYRdV7YNV/linux

$ ls -al linux
-rw-r--r-- 1 nathan nathan 10847776 Apr  6 11:31 linux
```
