### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#472]
https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/3479468988/jobs/5824732926

all the 5.15 builds failed with:
```
Traceback (most recent call last):
  File "/__w/continuous-integration2/continuous-integration2/./check_logs.py", line 267, in <module>
    build = verify_build()
  File "/__w/continuous-integration2/continuous-integration2/./check_logs.py", line 58, in verify_build
    build = get_build()
  File "/__w/continuous-integration2/continuous-integration2/utils.py", line 148, in get_build
    for build in _read_builds():
  File "/__w/continuous-integration2/continuous-integration2/utils.py", line 121, in _read_builds
    builds = json.load(f)
  File "/usr/lib/python3.[10](https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/3479468988/jobs/5824732926#step:5:11)/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
we should perhaps first check that the file is not empty before trying to decode it, and fail more gracefully with a concise error message.

**Comment by nathanchance** [comment]
> we should perhaps first check that the file is not empty before trying to decode it, and fail more gracefully with a concise error message.

Sure, we can do that but TuxSuite needs to just not generate an empty `builds.json` file. I have reopened https://gitlab.com/Linaro/tuxsuite/-/issues/179.

**Comment by nathanchance** [comment]
We won't hit this again after https://github.com/ClangBuiltLinux/continuous-integration2/commit/25e29380128fe9db2c7c19936445656d101830ab.
