### ISSUE TITLE
KeyError: 'tuxbuild_status'

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#545]
some cros jobs are failing

https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/4550837163/jobs/8029983671#step:5:16

```
Run ./check_logs.py
Traceback (most recent call last):
  File "/__w/continuous-integration2/continuous-integration2/./check_logs.py", line 272, in <module>
    verified_build = verify_build()
  File "/__w/continuous-integration2/continuous-integration2/./check_logs.py", line 5[9](https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/4550837163/jobs/8029983671#step:5:10), in verify_build
    if build["tuxbuild_status"] == "complete":
KeyError: 'tuxbuild_status'
```
did the schema of builds.json change?

**Comment by nickdesaulniers** [comment]
The tuxsuite [job](https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/4550837163/jobs/8024240338) has:
```
Error: Build timed out after 240.0 minutes; abandoning
```

**Comment by nathanchance** [comment]
Seems like `tuxsuite` timed out based on its output. It is probably a ChromeOS git caching problem, they have mentioned it a few times.

**Comment by nickdesaulniers** [comment]
https://tuxapi.tuxsuite.com/v1/groups/clangbuiltlinux/projects/continuous-integration2/builds/2Ng97bBKqmv8BGMkClzGwDMji82 -> status.json

has

```json
    "tuxbuild_status": "complete",
```

**Comment by vishalbhoj** [comment]
This regression was due to a large chromium kernel tree cache in the tuxsuite backend. I did the cleanup and the build finished after the cli timeout.
