### ISSUE TITLE
TypeError: 'usedForSecurity' is an invalid keyword argument for new()

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/continuous-integration2#98]
On Arch Linux, I get the following traceback:

```
$ ./generate_workflow.py < generator.yml mainline
Traceback (most recent call last):
  File "/home/nathan/cbl/github/ci/./generate_workflow.py", line 200, in <module>
    print_builds(config, args.tree)
  File "/home/nathan/cbl/github/ci/./generate_workflow.py", line 177, in print_builds
    check_logs_defconfigs.update(get_steps(build, "defconfigs"))
  File "/home/nathan/cbl/github/ci/./generate_workflow.py", line 133, in get_steps
    sanitize_job_name(name): {
  File "/home/nathan/cbl/github/ci/./generate_workflow.py", line 95, in sanitize_job_name
    h = hashlib.new("md5", name.encode("utf-8"), usedForSecurity=False)
  File "/usr/lib/python3.9/hashlib.py", line 160, in __hash_new
    return _hashlib.new(name, data, **kwargs)
TypeError: 'usedForSecurity' is an invalid keyword argument for new()
```

@nickdesaulniers do we need this option or can we just drop it?

**Comment by nickdesaulniers** [comment]
we can drop it, IIRC it was meant for speed of generating hashes
